# Generated by Django 5.2.6 on 2025-09-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='Time limit for this question in seconds'),
        ),
    ]
