# Generated by Django 5.2.6 on 2025-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=15, help_text='Time limit for this question in seconds'),
        ),
    ]
