# Generated by Django 5.2.6 on 2025-11-14 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_difficulty_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchmaking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player1_score', models.IntegerField(blank=True, null=True)),
                ('player2_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for player 2'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmakings', to='quiz.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
