# Generated by Django 5.2.6 on 2025-11-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_matchmaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='selected_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
