# Generated by Django 5.2.6 on 2025-11-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizresult_selected_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='explanation',
            field=models.TextField(blank=True, help_text='Brief explanation or answer shown on results page', null=True),
        ),
    ]
