# Generated by Django 5.2.6 on 2025-11-14 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quiz_options_quiz_created_at_quiz_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('10_wins', '10 Wins'), ('50_wins', '50 Wins'), ('100_wins', '100 Wins'), ('perfect_score', 'Perfect Score'), ('streak_3', '3-Quiz Streak'), ('streak_10', '10-Quiz Streak'), ('all_difficulties', 'Master of All'), ('speed_demon', 'Speed Demon'), ('comeback_king', 'Comeback King')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon name for badge (e.g., trophy, star, bolt)', max_length=50)),
                ('color', models.CharField(choices=[('success', 'Green'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan'), ('dark', 'Dark')], default='warning', max_length=20)),
            ],
            options={
                'ordering': ['badge_type'],
            },
        ),
        migrations.CreateModel(
            name='ShareableResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, help_text='Custom message with result', max_length=500, null=True)),
                ('is_public', models.BooleanField(default=True, help_text="Visible on user's profile")),
                ('views_count', models.IntegerField(default=0)),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='quiz.quizresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['follower'], name='quiz_userfo_followe_1cb630_idx'), models.Index(fields=['following'], name='quiz_userfo_followi_fbbc74_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
