# Generated by Django 5.2.6 on 2025-11-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_passwordreset_emailnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0, help_text='Failed verification attempts')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
